version: '3.8'

services:
  # Django API сервис
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - /app/__pycache__
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=core.settings
      - DATABASE_URL=sqlite:///db.sqlite3
    env_file:
      - .env
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    networks:
      - app-network

  # React фронтенд сервис
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000/api
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
    networks:
      - app-network
    command: npm run dev -- --host 0.0.0.0

  # База данных (опционально - PostgreSQL)
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: